server:
  port: 25000
spring:
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  rabbitmq:
    virtual-host: /
    host: 192.168.71.128
    port: 5672
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: 192.168.71.128
    port: 6379